name: Python CI/CD

on:
  push:
    branches:
      - main        # Change to your default branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use whichever version you need

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make install

      - name: Run tests
        run: make test

  build-docs:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main' # Only deploy from main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Define your deployment commands here"
          # Example:
          # scp dist/myapp.whl user@server:/path/to/deploy
          # ssh user@server "systemctl restart myapp"